### PR TITLE
Documenting/implementing an inter-plugin API.

### PR DESCRIPTION
**Pull request by Athanasius**
One plugin author asked questions about how to do inter-plugin IPC, so let's define that, adding a helper method in plug.py as well.

### CODE REVIEW

**Comment by inorton** [comment]
This would be quite nice, a kind of message broker perhaps?   EDMCOverlay would like this

**Comment by Karmak23** [comment]
Yup, i'm developing a plugin ; for now I don't have the use for an IPC mechanism because i'm just starting to design/code, but that could be cool if there existed one.

**Comment by A-UNDERSCORE-D** [comment]
@inorton / @Karmak23 I started a discussion on this here: https://github.com/EDCD/EDMarketConnector/discussions/885

**Comment by Athanasius** [comment]
Closing this in favour of the more recent discussion.

**Pull request closed without merging**
