### PR TITLE
Add .gitversion file to Linux archive

### PR DESCRIPTION
**Pull request by dvdmuckle**
Also renames a couple things in the GHA workflow file for building after a release.

### CODE REVIEW

**Comment by dvdmuckle** [comment]
I need to do some additional tests but this is how I'm looking to address #1827

**Comment by Rixxan** [comment]
This all looks good so far. Let me know when your testing is complete and I'll do my own passes through it :)

**Comment by dvdmuckle** [comment]
Finished my testing! I undid the renames I mentioned in the PR comment, as I didn't realize renaming GHA workflows changes the link to them.

**Comment by dvdmuckle** [comment]
Realized from the comment you left on #1827 that the checks should be done in the other order (IE, check for `git rev-parse --short HEAD`, then fall back to `.gitversion` if we don't get a valid git sha back). I can change the behavior here if you want.

**Comment by Rixxan** [comment]
Ideally, yes the preference should be the git HEAD, and then the .gitversion file, and then an error out to "unknown".

**Comment by dvdmuckle** [comment]
@Rixxan Done!

**Review by Rixxan — APPROVED** [review]
Changes look good to me! Thanks for contributing this.

**Pull request merged**
