### PR TITLE
EngineerProgress: Extra validation paranoia

### PR DESCRIPTION
**Pull request by Athanasius**
This is an example of just how icky it gets validating an event by hand.

Technically we need a function, many would probably be lengthier andmore complex than this one, for **every   single   journal   event  type**.

### CODE REVIEW

**Review by A-UNDERSCORE-D — APPROVED** [review]
Looks okay, though chunks of that nested if can probably be converted to ands

**Comment by Athanasius** [comment]
> Looks okay, though chunks of that nested if can probably be converted to ands

I like such nested conditionals for extra clarity, indent makes it very obvious that the second part depends on the first.

In the long run I suspect I'm going to have to knuckle down and write all those JSON schemas to validate against.  This was bad enough with the Rank/Progress caveats.  It'll long-term be cleaner to just have a "journal-schemas/2 directory with a file per event type to throw through the available JSON validator module.

**Comment by A-UNDERSCORE-D** [comment]
ah okay, I was poking at doing something for that but if a validator exists it'll be far better than anything that I can come up with _anyway_

**Comment by Athanasius** [comment]
> ah okay, I was poking at doing something for that but if a validator exists it'll be far better than anything that I can come up with _anyway_

See WIP https://github.com/Athanasius/ed-journal-verify

**Pull request merged**
