### PR TITLE
Enhancement/remove keyring

### PR DESCRIPTION
**Pull request by A-UNDERSCORE-D**
Removed keyring dependency
    
This removes all dependencies on the keyring lib, updates the requirements.txt to reflect that, and ensures that setup.py does not
attempt to package it.
    
Any use of the "old" keyring code will now return None and warn about its deprecation.

### CODE REVIEW

**Comment by Athanasius** [comment]
I wonder if any plugin is making use of it.  We package it, so they could.

**Comment by A-UNDERSCORE-D** [comment]
That is true, maybe continue to package it? or package a wrapper that just exports all of its stuff, but throws up a warning?

**Comment by Athanasius** [comment]
I checked all the "works with Python 3.x" plugins from the wiki page, and none of them have the string 'keyring' in any file.

So feel free to remove it.  Anyone who it breaks it for can just package keyring in their plugin anyway.

**Comment by A-UNDERSCORE-D** [comment]
that being the case, merge away :D

**Pull request merged**
