### PR TITLE
[2051] Config Files Audit

### PR DESCRIPTION
**Pull request by Rixxan**
Broken out of #2068

# Description
This is a full-pass update to the core config files, containing a major SemVer-compliant logic overhaul to the files. These updates are intended to optimize existing code, update older Python 2 style code to more updated standards, and increase readability and compatibility. 

## Type of change
- Rewrite of Existing Code

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Multiple install runs, clean installs, self-updates, and others made to confirm functionality, including under a variety of existing pre-install situations. 
- All PyTest tests pass
- Tested by the EDMC Internal Alpha Group and initial bugs fixed.

### CODE REVIEW

**Comment by Rixxan** [comment]
Seems something is up with the Linux changes. Time to drill that one down...

**Comment by norohind** [comment]
Greetings. I was just wondering why to change type hints for *list*, *dict*, *type* to their deprecated alternatives in typing module? I honestly thought today it's common to migrate from *typing.\<type\>* to *types* itself as they now support subscripting.

**Comment by Rixxan** [comment]
Hey @norohind thanks for pointing that out. 

I'll be honest, my brain was still operating under the older Python 3.8 typing system. I'll look into the newer typing system and see if we're making an accidental reversion instead of a forwarding of the system.

**Comment by Rixxan** [comment]
As I can't actually get a working Linux instance up right now, rolling back the linux config checks as they are failing the tests. Only going to work on things I can actually test right now.

**Review by C1701D — COMMENTED** [review]
Looks good re functionality, some small thing re readability in ``config/__init__.py`` though.
Additionally you're moving back to the deprecated ``Optional[]`` in two files.

**Comment by Rixxan** [comment]
Updated as indicated. Oldstyles replaced and documentation added in lieu of removal. 

image

**Pull request merged**
