### PR TITLE
[2188] Support Translation Language Override

### LINKED ISSUE #2188: Support Translation Language Override
**Describe the enhancement**

As a plugin author, I have a requirement to temporarily override the EDMC language with a different language for translating certain strings.

**Expected behavior**

The `l10n.Translations.translate()` function should take a parameter for overriding the language.

**Considered workarounds**

With assistance from @Rixxan, I have written a function in my plugin that does this, but think this could be a useful enhancement to contribute to the wider EDMC project, so available to all plugin authors. 

**Additional context**

I intend to submit a PR to add this functionality.

### PR DESCRIPTION
**Pull request by aussig**
## Description
The default `l10n.Translations.translate()` function only works with the language currently selected by the user and loaded in `l10n.Translations.install()`. This PR adds an additional optional `lang` parameter to `translate()`  which, when passed will temporarily load an alternative language and translate the passed string using that language.
 
## Type of change
Enhancement

## Implementation notes
* Some flake8 issues were flagged with the pre-existing imports. These were fixed.
* Some flake8 issues were flagged with the Darwin imports. These were not fixed as Darwin will be removed in 2186.
* The existing `context` parameter, passed to the function, was not well documented so this has been rewritten. Also, this parameter was modified inside the function, to strip it down to just the plugin name, and then used. IMHO this creates difficult to read code so I have introduced a new `plugin_name` variable to the existing code, to take this value, and the original `context` parameter is now left untouched. 
* I noted the comment "# TODO: There is probably a better way to go about this now." against the above extraction of the plugin name from `context` and would be happy to include a rework of this line if you can let me know what's the latest thinking on the approach.
* Apologies for the automatic trailing space removals from `PLUGINS.md`, I didn't spot these on commit but they don't seem unreasonable as a cleanup?

 
## How has this been tested?
By running EDMC in various languages and by modifying a plugin to use the new optional parameter.

Resolves #2188

### CODE REVIEW

**Comment by Rixxan** [comment]
This in the pipe for review after #1812, @aussig this PR may require minor updates and edits after 1812 is merged due to potential conflicts.

**Comment by aussig** [comment]
No problem @Rixxan, I'll await the merge on that. I took the opportunity to update this PR to the latest `develop`, resolving one conflict with imports caused by the removal of Darwin, I've used the latest imports from `develop` (I note you are ignoring Flake8 rule I001 - import alpha ordering - so I did the same)

**Comment by Rixxan** [comment]
@aussig This is ready for a re-review given the new translation system. Just ping me when it's been given a once-over :)

**Comment by aussig** [comment]
@Rixxan I've merged in the latest changes to `develop`, adding in the optional `lang` parameter to the new `tl()`.

**Comment by Rixxan** [comment]
Love it! Great work. Seems to test fine on my end.

**Pull request merged**
